R Matricies

In [2]:
#Matricies follow one datatype and have similar constraints as vectors
#Range of sequential numeric values
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [3]:
#Assign sequential numerica range to a vector
v <- 1:10
v

[1]  1  2  3  4  5  6  7  8  9 10

In [4]:
#matrix() functions
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [5]:
matrix(v, nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [7]:
matrix(v, byrow=T, nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [8]:
matrix(1:12, byrow = T, nrow = 4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [11]:
Lewiston <- c(12,14,18,13,17)
Rocky.Mount <- c(11,19,21,15,18)
Whiteville <- c(14,17,23,11,9)

In [12]:
weights <- c(Lewiston, Rocky.Mount, Whiteville)

In [13]:
weights

[1] 12 14 18 13 17 11 19 21 15 18 14 17 23 11  9

In [14]:
weights.matrix <- matrix(weights, byrow = T, nrow = 3)

In [15]:
weights.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 12   14   18   13   17  
[2,] 11   19   21   15   18  
[3,] 14   17   23   11    9

In [18]:
#name row = rownames(), columns = colnames()
days <- c('M','T','W','Th','F')
loc.names <- c("Lewiston", "RockyMount", "Whiteille")

In [19]:
colnames(weights.matrix) <- days

In [22]:
rownames(weights.matrix) <- loc.names

In [23]:
weights.matrix

M  T  W  Th F 
Lewiston   12 14 18 13 17
RockyMount 11 19 21 15 18
Whiteille  14 17 23 11  9

In [24]:
#a matrix with 5 rows and 10 columns
mat <-matrix(1:50, byrow = T, nrow=5)

In [26]:
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [27]:
2*mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [28]:
mat/2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  0.5  1    1.5  2    2.5  3    3.5  4    4.5  5   
[2,]  5.5  6    6.5  7    7.5  8    8.5  9    9.5 10   
[3,] 10.5 11   11.5 12   12.5 13   13.5 14   14.5 15   
[4,] 15.5 16   16.5 17   17.5 18   18.5 19   19.5 20   
[5,] 20.5 21   21.5 22   22.5 23   23.5 24   24.5 25

In [29]:
#the comparison operators (==, !=, >,<,>=,<=)
mat ^2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81  100 
[2,]  121  144  169  196  225  256  289  324  361  400 
[3,]  441  484  529  576  625  676  729  784  841  900 
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500

In [30]:
mat > 15

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
[1,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [31]:
mat +mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [32]:
mat/mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    1    1    1    1    1    1    1    1    1    
[2,] 1    1    1    1    1    1    1    1    1    1    
[3,] 1    1    1    1    1    1    1    1    1    1    
[4,] 1    1    1    1    1    1    1    1    1    1    
[5,] 1    1    1    1    1    1    1    1    1    1

In [33]:
mat ^mat

[,1]         [,2]         [,3]         [,4]         [,5]        
[1,] 1.000000e+00 4.000000e+00 2.700000e+01 2.560000e+02 3.125000e+03
[2,] 2.853117e+11 8.916100e+12 3.028751e+14 1.111201e+16 4.378939e+17
[3,] 5.842587e+27 3.414279e+29 2.088047e+31 1.333736e+33 8.881784e+34
[4,] 1.706917e+46 1.461502e+48 1.291100e+50 1.175664e+52 1.102507e+54
[5,] 1.330878e+66 1.501309e+68 1.734377e+70 2.050774e+72 2.480636e+74
     [,6]         [,7]         [,8]         [,9]         [,10]       
[1,] 4.665600e+04 8.235430e+05 1.677722e+07 3.874205e+08 1.000000e+10
[2,] 1.844674e+19 8.272403e+20 3.934641e+22 1.978420e+24 1.048576e+26
[3,] 6.156120e+36 4.434265e+38 3.314552e+40 2.567686e+42 2.058911e+44
[4,] 1.063874e+56 1.055513e+58 1.075912e+60 1.125951e+62 1.208926e+64
[5,] 3.068035e+76 3.877924e+78 5.007021e+80 6.600972e+82 8.881784e+84

In [35]:
mat2 <- matrix(1:9, nrow=3)

In [36]:
mat2*mat2 #multiply the elements

[,1] [,2] [,3]
[1,] 1    16   49  
[2,] 4    25   64  
[3,] 9    36   81

In [37]:
#%*%, matrix multiplication
mat2 %*% mat2

[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150

In [38]:
weights.matrix

M  T  W  Th F 
Lewiston   12 14 18 13 17
RockyMount 11 19 21 15 18
Whiteille  14 17 23 11  9

In [40]:
colSums(weights.matrix)

M  T  W Th  F 
37 50 62 39 44

In [41]:
rowSums(weights.matrix)

Lewiston RockyMount  Whiteille 
        74         84         74

In [42]:
colMeans(weights.matrix)

M        T        W       Th        F 
12.33333 16.66667 20.66667 13.00000 14.66667

In [43]:
rowMeans(weights.matrix)

Lewiston RockyMount  Whiteille 
      14.8       16.8       14.8

In [44]:
#add the clayton location onto weights.matrix
Clayton <- c(17,23,15,19,13)


In [45]:
#cbind() or rbind()
ncsu.matrix <- rbind(weights.matrix, Clayton)

In [46]:
ncsu.matrix

M  T  W  Th F 
Lewiston   12 14 18 13 17
RockyMount 11 19 21 15 18
Whiteille  14 17 23 11  9
Clayton    17 23 15 19 13

In [47]:
Means.loc <- rowMeans(ncsu.matrix)

In [48]:
Means.loc

Lewiston RockyMount  Whiteille    Clayton 
      14.8       16.8       14.8       17.4

In [49]:
ncsu.matrix <- cbind(ncsu.matrix, Means.loc)

In [50]:
ncsu.matrix

M  T  W  Th F  Means.loc
Lewiston   12 14 18 13 17 14.8     
RockyMount 11 19 21 15 18 16.8     
Whiteille  14 17 23 11  9 14.8     
Clayton    17 23 15 19 13 17.4

In [51]:
short <- c(2,18,12)
long <- c(12, 11,10,9,8)

In [52]:
cbind(ncsu.matrix,short)

Warning message in cbind(ncsu.matrix, short):
"number of rows of result is not a multiple of vector length (arg 2)"

M  T  W  Th F  Means.loc short
Lewiston   12 14 18 13 17 14.8       2   
RockyMount 11 19 21 15 18 16.8      18   
Whiteille  14 17 23 11  9 14.8      12   
Clayton    17 23 15 19 13 17.4       2

In [53]:
cbind(ncsu.matrix,long)

Warning message in cbind(ncsu.matrix, long):
"number of rows of result is not a multiple of vector length (arg 2)"

M  T  W  Th F  Means.loc long
Lewiston   12 14 18 13 17 14.8      12  
RockyMount 11 19 21 15 18 16.8      11  
Whiteille  14 17 23 11  9 14.8      10  
Clayton    17 23 15 19 13 17.4       9

In [54]:
#example.matrix[row,col]
mat <-matrix(1:50, byrow =T, nrow = 5)

In [55]:
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [56]:
mat[1,]

[1]  1  2  3  4  5  6  7  8  9 10

In [57]:
mat[,1]

[1]  1 11 21 31 41

In [58]:
mat[1:3,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30

In [59]:
mat[1:2,1:3]

[,1] [,2] [,3]
[1,]  1    2    3  
[2,] 11   12   13

In [60]:
mat[,9:10]

[,1] [,2]
[1,]  9   10  
[2,] 19   20  
[3,] 29   30  
[4,] 39   40  
[5,] 49   50

In [63]:
#Factor and categorical matricies
#factor()

#Example: P(peanut), M(maize),S(soy), C(cotton)

crop <- c('P','P','C','M','C','S','P','S','M','P')
id <- c(1:10)

In [65]:
factor.crop <- factor(crop)

In [66]:
factor.crop

[1] P P C M C S P S M P
Levels: C M P S

In [67]:
ord.cat <- c('Cold','Med','Hot')

In [68]:
#ordered = TRUE
#levels = c('The order')
temps <- c('cold','hot','hot','med','cold','hot','med')

In [69]:
fact.temps <- factor(temps, ordered = T, levels=c('cold', 'med', 'hot'))

In [70]:
fact.temps

[1] cold hot  hot  med  cold hot  med 
Levels: cold < med < hot

In [71]:
#summary
summary(temps)

   Length     Class      Mode 
        7 character character 

In [72]:
summary(fact.temps)

cold  med  hot 
   2    2    3